### PR TITLE
Data for ICFP 2017

### PR DESCRIPTION
**Pull request by jegi**
Hi. Could you please add this data for [ICFP 2017](http://icfp17.sigplan.org/) to the Confero app?

Ta.

Jeremy

### CODE REVIEW

**Comment by rtholmes** [comment]
Merged. I will update the index file and get this fully deployed on Monday.

**Comment by jegi** [comment]
If I slightly revise the JSON data and you re-deploy it, does that erase all participants' preferences (in particular, starred talks)?

**Comment by rtholmes** [comment]
No, as long as the paper and person ids don't change preferences will be stable.

**Comment by jegi** [comment]
Great, ta. I hope to sort out some revisions shortly.

**Pull request merged**
